import path from "node:path";

import type { Line } from "./emit/context.mts";
import type { Expect, Invoke, Table } from "../dsl.import.meta.vitest.ts";

export const SUFFIX = ".namespace.test.ts";

const stemOf = (source: string) =>
  path.basename(source).replace(/\.[cm]?tsx?$/, "");

const slugOf = (testName: string) =>
  testName.replace(/[^\w[\]-]+/g, "_").replace(/^_+|_+$/g, "");

export const perTestFile = (source: string, testName: string, suffix: string) =>
  path.join(path.dirname(source), `${stemOf(source)}.${slugOf(testName)}${suffix}`);

export const idFor = (source: string, testName: string) =>
  perTestFile(source, testName, SUFFIX);

export const collectorLines = (
  imports: { id: string; line: number }[],
): Line[] => [
  { code: ``, line: null },
  {
    code: `// ───────── generated by namespace-tests; not part of your build ─────────`,
    line: null,
  },
  { code: `if (import.meta.vitest) {`, line: null },
  ...imports.map(({ id, line }) => ({
    code: `  await import(${JSON.stringify(id)});`,
    line,
  })),
  { code: `}`, line: null },
  { code: ``, line: null },
];

export const collected = (code: string, collector: Line[]) =>
  `${code}\n${collector.map((l) => l.code).join("\n")}`;

declare namespace idFor {
  /** beside the module, named for the module and the test */
  export type Names = Table<
    typeof idFor,
    [
      [
        args: ["src/counter.ts", "Counter > Chainable"],
        expected: "src/counter.Counter_Chainable.namespace.test.ts",
      ],
      [
        args: ["src/codec.mts", "encode > Tagged[1]"],
        expected: "src/codec.encode_Tagged[1].namespace.test.ts",
      ],
    ]
  >;
}

declare namespace collectorLines {
  type Block = Invoke<
    typeof collectorLines,
    [[{ id: "./a.namespace.test.ts"; line: 3 }]]
  >;

  /** the import is anchored to the line the test was written on */
  export type Anchored = Expect<
    Block,
    "matches",
    [
      { code: "" },
      { line: null },
      { code: "if (import.meta.vitest) {" },
      { code: '  await import("./a.namespace.test.ts");'; line: 3 },
      { code: "}" },
      { code: "" }
    ]
  >;
}
