import path from "node:path";
import {
  hasTest,
  type Analysis,
  type Import,
  type TestSnippet,
} from "./analyze.ts";
import { generatedId, importPath, testName } from "./names.ts";
import { generatedSourceMap } from "./sourcemap.ts";

/** A pocket's initial value, printed, and the value imports it needs. */
export type PocketValue = {
  initial: string;
  /** each member that has a value, printed */
  members: [member: string, value: string][];
  imports: Map<string, Set<string>>;
};

export type GenerateOptions = {
  /** Absolute path of the runtime module the generated file imports from. */
  runtime: string;
  /** Absolute path of the components index, for `typeof Sweater.<Component>` parameters. */
  components: string;
  /** Printed initial values, by pocket parameter name. */
  pockets: Map<string, PocketValue>;
  /** The file the component is served or written as: its in-memory id unless extracted. */
  at?: string;
};

const quote = (s: string) => JSON.stringify(s);

/** An import rewritten so that the names a snippet needs as values arrive as values. */
function printImport(i: Import, values: Set<string>): string {
  const spec = quote(i.specifier);
  if (!i.bindings.length) return `import ${spec};`;
  const lines: string[] = [];
  const typeNamed: string[] = [];
  const valueNamed: string[] = [];
  let typeDefault: string | null = null;
  let valueDefault: string | null = null;
  for (const b of i.bindings) {
    const asType = b.typeOnly && !values.has(b.local);
    if (b.kind === "namespace") {
      lines.push(
        `import ${asType ? "type " : ""}* as ${b.local} from ${spec};`,
      );
    } else if (b.kind === "default") {
      if (asType) typeDefault = b.local;
      else valueDefault = b.local;
    } else {
      const text =
        b.imported === b.local ? b.local : `${b.imported} as ${b.local}`;
      (asType ? typeNamed : valueNamed).push(text);
    }
  }
  const line = (type: boolean, def: string | null, named: string[]) => {
    const parts = [def, named.length ? `{ ${named.join(", ")} }` : null].filter(
      Boolean,
    );
    if (parts.length)
      lines.push(
        `import ${type ? "type " : ""}${parts.join(", ")} from ${spec};`,
      );
  };
  line(true, typeDefault, typeNamed);
  line(false, valueDefault, valueNamed);
  return lines.join("\n");
}

const indent = (text: string, by = "  ") =>
  text
    .split("\n")
    .map((l) => (l.trim() ? by + l : l))
    .join("\n");

/** The generated test component for one snippet, with a map back to the component. */
export function generate(
  analysis: Analysis,
  snippet: TestSnippet,
  options: GenerateOptions,
) {
  const { file, source } = analysis;
  const id = options.at ?? generatedId(file, snippet.name);
  const runtime = importPath(id, options.runtime);
  const sourceSpecifier = importPath(id, file);

  const values = new Set<string>();
  const args: string[] = [];
  const extraImports = new Map<string, Set<string>>();
  let sweater = false;
  for (const p of snippet.params) {
    if (p.kind === "subject") {
      values.add(analysis.self!);
      args.push(analysis.self!);
    } else if (p.kind === "value") {
      values.add(p.local);
      args.push(p.local);
    } else if (p.kind === "pocket") {
      const value = options.pockets.get(p.name);
      args.push(`__pocket<${p.typeText}>(${value?.initial ?? "{}"})`);
      for (const [specifier, bindings] of value?.imports ?? [])
        extraImports.set(
          specifier,
          new Set([...(extraImports.get(specifier) ?? []), ...bindings]),
        );
    } else if (p.kind === "sweater") {
      sweater = true;
      args.push(`__Sweater.${p.member}`);
    } else if (p.kind === "test") args.push("__harness.test");
    else args.push("undefined");
  }

  const imports = analysis.imports
    .map((i) => printImport(i, values))
    .filter(Boolean);
  for (const [specifier, bindings] of extraImports)
    imports.push(
      `import { ${[...bindings].join(", ")} } from ${quote(specifier)};`,
    );

  const meta = {
    name: testName(file, snippet.name),
    source: sourceSpecifier,
    snippet: snippet.name,
    line: snippet.line,
    test: hasTest(snippet),
  };

  const lang = analysis.instance?.lang ?? analysis.module?.lang ?? "ts";
  const langAttr = ` lang="${lang}"`;

  const head = [
    `<!-- generated by sweater-vest from ${sourceSpecifier} > ${snippet.name}; not part of your build -->`,
    `<script${langAttr} module>`,
    `  import { define as __define } from ${quote(runtime)};`,
    `  import __Self from ${quote(`./${path.basename(id)}`)};`,
    ``,
    `  // a thunk: in the browser the module's own default export is not initialised yet`,
    `  __define(() => __Self, ${JSON.stringify(meta)});`,
    `</script>`,
    ``,
    `<script${langAttr}>`,
    `  import { pocket as __pocket, type Harness as __Harness } from ${quote(runtime)};`,
    ...(sweater
      ? [
          `  import * as __Sweater from ${quote(importPath(id, options.components))};`,
        ]
      : []),
    indent(imports.join("\n")),
    ``,
    `  let { harness: __harness }: { harness: __Harness } = $props();`,
    `</script>`,
    ``,
  ];
  // the snippet was written under the component's styles, so it keeps them; what it does not use is no mistake
  const css = analysis.css
    ? [
        ``,
        `<!-- svelte-ignore css_unused_selector -->`,
        source.slice(analysis.css.start, analysis.css.end),
      ]
    : [];
  const lines = [
    ...head,
    source.slice(snippet.start, snippet.end),
    ``,
    `{@render ${snippet.name}(${args.join(", ")})}`,
    ...css,
    ``,
  ];
  const code = lines.join("\n");
  const map = generatedSourceMap(
    id,
    code,
    { file, text: source },
    {
      generatedLine: head.join("\n").split("\n").length,
      sourceStart: snippet.start,
      sourceEnd: snippet.end,
    },
  );
  return { code, map };
}

import type {
  Expect,
  Invoke,
} from "../../suede.nests.sweater-vest/dsl.import.meta.vitest.ts";
import type { generated, generatedWhole } from "../_internal/harness.ts";

declare namespace generate {
  type Markup = `
{#snippet simple(C: typeof Self, pocket: { n: 2; el: HTMLDivElement }, test: Test)}
  <C bind:this={pocket.el} />
  {test(async () => {})}
{/snippet}
`;

  type Code = Invoke<
    typeof generated,
    [Markup, "simple", { pocket: "{ n: 2 }" }]
  >;

  /** the component's own type import becomes a value import, under the same name */
  export type SelfAsValue = Expect<
    Code,
    "includes",
    'import Self from "./Probe.svelte";'
  >;

  /** the DSL stays a type import */
  export type DslStaysType = Expect<
    Code,
    "includes",
    'import type { Test, Widen, Sweater } from "../lib/dsl.import.meta.vitest";'
  >;

  /** the snippet is copied as written */
  export type Verbatim = Expect<
    Code,
    "includes",
    "<C bind:this={pocket.el} />"
  >;

  /** and rendered with the component, its pocket, and the harness's test */
  export type Rendered = Expect<
    Code,
    "includes",
    "{@render simple(Self, __pocket<{ n: 2; el: HTMLDivElement }>({ n: 2 }), __harness.test)}"
  >;

  /** it registers itself, through a thunk, with where it came from */
  export type Registers = Expect<
    Code,
    "includes",
    '__define(() => __Self, {"name":"Probe > simple","source":"./Probe.svelte","snippet":"simple","line":6,"test":true});'
  >;

  type ValueScript = `
import type { fakeData, Shape } from "./harness.ts";
import type * as ns from "./ns.ts";
`;

  type Values = `
{#snippet v(C: typeof Self, data: typeof fakeData, test: Test)}
  <C />
  {test(async () => {})}
{/snippet}
`;

  type ValueCode = Invoke<typeof generated, [Values, "v", {}, ValueScript]>;

  /** of a type-only import, the names a snippet takes as values are imported as values; the rest stay types */
  export type Split = [
    Expect<ValueCode, "includes", 'import type { Shape } from "./harness.ts";'>,
    Expect<ValueCode, "includes", 'import { fakeData } from "./harness.ts";'>,
    Expect<ValueCode, "includes", 'import type * as ns from "./ns.ts";'>,
    Expect<
      ValueCode,
      "includes",
      "{@render v(Self, fakeData, __harness.test)}"
    >,
  ];
}

declare namespace generate {
  type WithStatus = `
{#snippet shown(C: typeof Self, Status: typeof Sweater.Status, test: Test)}
  <Status {test} />
  <C />
  {test(async () => {})}
{/snippet}
`;

  type StatusCode = Invoke<typeof generated, [WithStatus, "shown"]>;

  /** a library component comes from the components index, under the namespace the snippet wrote */
  export type Components = [
    Expect<
      StatusCode,
      "includes",
      'import * as __Sweater from "../lib/components/index.ts";'
    >,
    Expect<
      StatusCode,
      "includes",
      "{@render shown(Self, __Sweater.Status, __harness.test)}"
    >,
  ];

  type Styled = `<script lang="ts">
  import type Self from "./Probe.svelte";
  import type { Test } from "../lib/dsl.import.meta.vitest";
</script>
{#snippet s(C: typeof Self, test: Test)}
  <div class="frame"><C /></div>
  {test(async () => {})}
{/snippet}
<style>
  .frame { padding: 1rem; }
</style>
`;

  /** the component's styles come along, since the snippet's markup was written under them */
  export type KeepsStyle = Expect<
    Invoke<typeof generatedWhole, [Styled, "s"]>,
    "includes",
    "<!-- svelte-ignore css_unused_selector -->\n<style>\n  .frame { padding: 1rem; }\n</style>"
  >;
}
