import MagicString from "magic-string";
import type { Analysis } from "./analyze.ts";

/**
 * The component as a build sees it: every test snippet removed. A test
 * snippet is never rendered, but the compiler still emits it (its template is
 * hoisted to module scope), so it has to be taken out before compilation.
 */
export function scrub(analysis: Analysis, collector: string | null = null) {
  const s = new MagicString(analysis.source);
  for (const snippet of analysis.snippets) {
    let end = snippet.end;
    // take the line break after it too, so no blank line is left behind
    if (analysis.source[end] === "\n") end += 1;
    else if (analysis.source.startsWith("\r\n", end)) end += 2;
    s.remove(snippet.start, end);
  }
  if (collector) {
    const { module, instance } = analysis;
    if (module) s.appendLeft(module.contentEnd, `\n${collector}\n`);
    else {
      const lang = instance?.lang ? ` lang="${instance.lang}"` : "";
      s.prepend(`<script${lang} module>\n${collector}\n</script>\n\n`);
    }
  }
  return {
    code: s.toString(),
    map: s
      .generateMap({ hires: true, source: analysis.file, includeContent: true })
      .toString(),
  };
}

import type {
  Expect,
  Invoke,
} from "../../suede.nests.sweater-vest/dsl.import.meta.vitest.ts";
import type { scrubbed } from "../_internal/harness.ts";

declare namespace scrub {
  type Source = `<script lang="ts">
  import type Self from "./Probe.svelte";
  import type { Test } from "../lib/dsl.import.meta.vitest";
  let { n }: { n: number } = $props();
</script>

{#snippet simple(C: typeof Self, test: Test)}
  <C />
{/snippet}

<p>{n}</p>
`;

  type Built = Invoke<typeof scrubbed, [Source]>;

  /** a build sees the component without its test snippets, and nothing else changed */
  export type Removed = [
    Expect<Built, "excludes", "{#snippet">,
    Expect<Built, "includes", "<p>{n}</p>">,
    Expect<Built, "includes", "let { n }: { n: number } = $props();">,
    Expect<Built, "excludes", "import.meta.vitest) {">,
  ];

  type Collected = Invoke<typeof scrubbed, [Source, true]>;

  /** Vitest sees the same, plus a module script that imports one generated test per snippet */
  export type Collector = [
    Expect<Collected, "startsWith", '<script lang="ts" module>'>,
    Expect<
      Collected,
      "includes",
      'if (import.meta.vitest) {\n  await import("./Probe.simple.vest.svelte");\n}'
    >,
    Expect<Collected, "excludes", "{#snippet">,
  ];

  type WithModule = `<script lang="ts" module>
  export const shared = 1;
</script>
<script lang="ts">
  import type Self from "./Probe.svelte";
  import type { Test } from "../lib/dsl.import.meta.vitest";
</script>
{#snippet simple(C: typeof Self, test: Test)}
  <C />
{/snippet}
`;

  /** an existing module script takes the collector at its end */
  export type Appended = Expect<
    Invoke<typeof scrubbed, [WithModule, true]>,
    "includes",
    "export const shared = 1;\n\n// ───────── generated by sweater-vest; not part of your build ─────────\nif (import.meta.vitest) {"
  >;
}
